### PR TITLE
Tweak dependencies and testcases

### PR DESCRIPTION
**Pull request by cosmo0920**
Hi, I've found that this plugin has some problem to use with Fluentd v0.14 compat layer.
Fluentd v0.10 is already EOL.
Its plugins should depend on v0.12 or later.

Perhaps, this PR contains a bit of big changes.
Could you review this PR?

I hope that this plugin will work with v0.14 compat layer.

Thanks,

### CODE REVIEW

**Comment by cosmo0920** [comment]
Closing this in favor of #5.

**Comment by cosmo0920** [comment]
@fujimotos Current master is still unusable on current Fluentd v0.12.x because lack of `require "fluent/input"` in in_nsq.
Could you work on this?
Or, v0.12 support should drop after v1 migration?

**Comment by fujimotos** [comment]
> Current master is still unusable on current Fluentd v0.12.x because lack of require "fluent/input" in in_nsq.

AFAICT, `fluent-plugin-nsq` works fine with Fluentd v0.12.X.
(In fact, I can confirm this with Fluentd v0.12.42 in my local environment)

If you are meaning Fluentd > v0.14, then yes. It does not work well.
I'm currently inclined to do something like below:

 1. Merge #6 and release fluent-plugin-nsq v0.0.7, which becomes the last version
     supporting Fluentd v0.12.
 2. Migrate the plugin to Fluentd v1.0 API and release the new major version (maybe v1.0.0, I guess?).
       - Hereafter, fluent-plugin-nsql only support v0.14 or later.

What do you think about the plan above?

**Comment by cosmo0920** [comment]
> 1. Merge #6 and release fluent-plugin-nsq v0.0.7, which becomes the last version
>     supporting Fluentd v0.12.
> 2. Migrate the plugin to Fluentd v1.0 API and release the new major version (maybe v1.0.0, I guess?).
>         Hereafter, fluent-plugin-nsql only support v0.14 or later.
> 
> What do you think about the plan above?

Looks good. But Only #6's patch does not run test cases with `bundle install --path vendor/bundle`.
We need to add `test-unit` and `minitest` into development dependencies.

**Comment by fujimotos** [comment]
OK. The test is fixed by #7, and we can confirm the plugin now works fine with all active
Ruby versions (2.3/2.4/2.5).

**Pull request closed without merging**
